### ISSUE TITLE
latest commit break git-fat find

### ISSUE THREAD

**Issue by isuruf** [jedbrown/git-fat#74]
```
$python git-fat find 1000000
Traceback (most recent call last):
  File "git-fat", line 616, in <module>
    fat.cmd_find(sys.argv[2:])
  File "git-fat", line 540, in cmd_find
    for path, sizes in sorted(pathsizes.items(), key=lambda p,s: max(s), reverse=True):
TypeError: <lambda>() takes exactly 2 arguments (1 given)
```

**Comment by isuruf** [comment]
Changing line 540 to `for path, sizes in sorted(pathsizes.items(), key=lambda s: max(s), reverse=True)` works

**Comment by jedbrown** [comment]
Thanks. Your suggestion needed a tweak to get the correct sort order.

**Comment by isuruf** [comment]
Thanks.
