### ISSUE TITLE
Push, pull and gc commands result in the following error

### ISSUE THREAD

**Issue by Alexarea02** [jedbrown/git-fat#97]
```
$ git fat push
Traceback (most recent call last):
  File "C:\Program Files\Python27\Scripts\git-fat", line 1121, in <module>
    main()
  File "C:\Program Files\Python27\Scripts\git-fat", line 1110, in main
    run(backend, **kwargs)
  File "C:\Program Files\Python27\Scripts\git-fat", line 991, in run
    getattr(gitfat, fn)(**kwargs)
  File "C:\Program Files\Python27\Scripts\git-fat", line 905, in push
    files = self._referenced_objects(**kwargs) & self._cached_objects()
  File "C:\Program Files\Python27\Scripts\git-fat", line 535, in _referenced_objects
    objs_dict = self._managed_files(**kwargs)
  File "C:\Program Files\Python27\Scripts\git-fat", line 593, in _managed_files
    for objhash, objtype, size in revlistgen:
  File "C:\Program Files\Python27\Scripts\git-fat", line 557, in _rev_list
    awk = sub.Popen([awk_tool, '{print $1}'], stdin=revlist.stdout, stdout=sub.PIPE)
  File "C:\Program Files\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Program Files\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```
Any idea why this might be ?

**Comment by Alexarea02** [comment]
Is there anybody that had this problem before? I am still fighting with this error.

**Comment by mahimahi42** [comment]
I am also experiencing this error on Windows with Python 2.7.5, have been attempting to troubleshoot but no success yet.

**Comment by mahimahi42** [comment]
Did end up finding a work-around for using git-fat, though it is obtuse.

1. Install Cygwin with the following packages:
    a. git
    b. python2
    c. rsync
2. Add the following to Cygwin's `.bashrc`: `export PATH="<path to directory with git-fat script>:$PATH"`.
3. Either restart Cygwin command line or run `source ~/.bashrc`.
4. git-fat should now work.

**Comment by mahimahi42** [comment]
The cause of the underlying issue is a lack of `rsync` on Windows. I attempted a few sets of instructions of adding `rsync` to the MSYS installation provided by Git for Windows, but was unable to find a working solution. Going through Cygwin did work relatively out of the box.
